import React from 'react'

export default () => <div>
  <h2>React project structure</h2>

  <p>After you run <code>fronthack init</code> command and select <em>React</em>, you will find a following file structure of the project. It is very similar to the one, you can know from <strong>create-react-app</strong>.</p>

  <h2>public/</h2>

  <p>Static assets for the site, that does not need to be transpiled by babel.</p>

  <h2>src/</h2>

  <p>Contains js code that must be transpiled by babel and styles written in Sass.Initially in may contain following elements:</p>

  <ul>
    <li><em><strong>style/</strong></em> - global styles, variables, helper classes, mixins.</li>
    <li><em><strong>components/</strong></em> - React components generated by frondhack lands here.</li>
    <li><em><strong>App.js</strong></em> - to level app component, where JSX sctructure starts.</li>
    <li><em><strong>index.js</strong></em> - entry point of React app.</li>
    <li><em><strong>serwiceWorker.js</strong></em> - service worker configuration</li>
  </ul>

  <h2>designs/</h2>

  <p>Put designs here to display them behind the content of a page. More in <strong>Recognition of designs</strong> chapter.</p>

  <h2>build/</h2>

  <p>Full self-sufficient output directory, ready to be hosted on a production server. It contains minified code.</p>


  <h2>./</h2>

  <p>Another elements in the root directory:</p>

  <ul>
    <li><em><strong>.fronthack</strong></em> - flags dir as a Fronthack project and contains metadata required for fronthack CLI to work.</li>
    <li><em><strong>.htmlhintrc</strong></em> - HTMLHint configuration file.</li>
    <li><em><strong>.sasslintrc</strong></em> - Sass Lint configuration file.</li>
    <li><em><strong>webpack.common.js</strong></em> - common webpack configuration file.</li>
    <li><em><strong>webpack.dev.js</strong></em> - webpack configuration file for development script only.</li>
    <li><em><strong>webpack.prod.js</strong></em> - webpack configuration file for production script only.</li>
  </ul>
</div>
